<!-- main menu -->
<table width="100%" cellspacing="0" cellpadding="0">
<tr>
<td align="left"></td>
<td align="right">
<a href="docmgmtin.php"><img src="images/in.jpg" width=65 height=65 alt="Check In" border=0></a>&nbsp;&nbsp;<a href="docmgmtsearch.php"><img src="images/search.jpg" width=65 height=65 alt="Search" border=0></a>&nbsp;<a href="docmgmtadd.php"><img src="images/add.jpg" width=65 height=65 alt="Add" border=0></a>
</td>
</tr>
</table>
